server:
  port: 8082

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/khuative/java-api-test-config
          clone-on-start: true
          default-label: main